### ISSUE TITLE
Request for a license text

### ISSUE THREAD

**Issue by ZephyrThing** [marcolanaro/JS-Fuzzy#4]
Good day! 

I really love your JS code to implement the Fuzzy Logic. For me, it is easy to understand and to apply too. Thanks for sharing such a great work! 

Meanwhile, I wish to apply and slightly modify your code for my academic research in using Fuzzy Logic.  My modification is focus on changing the use of Combs Method to using Conjunction operator for combining more than one input variable in fuzzy rules for fuzzy inference process. 

Therefore, I would like to ask for a license text to be added into your code, so that I could have your permission to use your code and credit your works properly in my research.

Thanks.

**Comment by marcolanaro** [comment]
Hi @ZephyrThing,
sorry for the late answer, but I'm very busy in this period.

I'm happy to hear you want to improve the library. I'm actually thinking that this little project has never been completed with license, unit tests, npm, CI builder, ecc.
For the moment I've added the license, so you can start contributing.

Please go ahead with small PRs and a little change per time.
If you need any help, I'm happy to assist you.
Regards

**Comment by ZephyrThing** [comment]
Hi @marcolanaro  !

A belated, but heartfelt thank you for your permission to use your code, and the MIT license. It is really a great help from you. I am sorry for my late gratitude due to my research projects, but with respect, I am delighted that I could properly credit your works in my research now. 

Regards
